# Shared plumbing for the CIPP -> IT Glue documentation assets (Intune, Identity, and the
# email/security and tenant documents to come). Each document differs only in its report
# model, its trait map and its asset type; the identity block, the completeness notes and
# the upsert are identical, so they live here once rather than being copied per document.

function Get-ITGlueDocumentIdentityTraits {
    <#
    .SYNOPSIS
        The four identity traits every documentation asset carries.
    .DESCRIPTION
        Tenant, domain, last-synced and the object count. Times are US Central per the
        house standard - the person reading the record is in Texas, not UTC.

        The count trait is written as a string: IT Glue renders a Number field as "75.0".
    .FUNCTIONALITY
        Internal
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]$Model,
        [string]$CountTrait = 'policy-count'
    )

    $CentralZone = try { [System.TimeZoneInfo]::FindSystemTimeZoneById('America/Chicago') } catch {
        try { [System.TimeZoneInfo]::FindSystemTimeZoneById('Central Standard Time') } catch { $null }
    }
    $Now = if ($CentralZone) {
        [System.TimeZoneInfo]::ConvertTimeFromUtc([datetime]::UtcNow, $CentralZone)
    } else { [datetime]::UtcNow }
    $Abbrev = if (-not $CentralZone) { 'UTC' } elseif ($CentralZone.IsDaylightSavingTime($Now)) { 'CDT' } else { 'CST' }

    $Traits = @{
        'tenant'        = [string]$Model.TenantName
        'tenant-domain' = [string]$Model.TenantDomain
        'last-synced'   = ('{0} {1}' -f $Now.ToString('yyyy-MM-dd HH:mm'), $Abbrev)
    }
    $Traits[$CountTrait] = [string][int]$Model.ObjectCount
    return $Traits
}

function Get-ITGlueCollectionNotesHtml {
    <#
    .SYNOPSIS
        Render the Collection Notes block: what the record does not contain, and why.
    .DESCRIPTION
        Every documentation record states its own completeness. A section that failed to
        collect and a section that was truncated are both recorded here, so a reader can
        tell "this client has none of that" apart from "we could not read it" without
        leaving IT Glue. An empty notes list still emits the source disclaimer.
    .FUNCTIONALITY
        Internal
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]$Model,
        [System.Collections.Generic.List[object]]$Truncations,
        [string]$SourceLabel = 'configuration'
    )

    $Rows = [System.Collections.Generic.List[string]]::new()
    foreach ($N in @($Model.CollectionNotes)) {
        $Rows.Add((Get-ITGlueFormattedField -Title "$($N.Section) (not collected)" -Value "$($N.Detail)"))
    }
    foreach ($N in @($Truncations)) {
        if ($null -eq $N) { continue }
        $Rows.Add((Get-ITGlueFormattedField -Title "$($N.Section) (truncated)" -Value "$($N.Detail)"))
    }
    if ($Rows.Count -eq 0) {
        $Rows.Add((Get-ITGlueFormattedField -Title 'Completeness' -Value 'Every section was collected in full.'))
    }
    $Rows.Add((Get-ITGlueFormattedField -Title 'Source' -Value ("Generated by CIPP from live Microsoft Graph data for $($Model.TenantDomain). This record documents $SourceLabel and is overwritten on every sync - make changes in Microsoft 365, not here.")))

    return Get-ITGlueFormattedBlock -Heading 'Collection Notes' -Body ($Rows -join "`n")
}

function Set-ITGlueDocumentAsset {
    <#
    .SYNOPSIS
        Upsert a per-client documentation asset: one record per organisation and type.
    .DESCRIPTION
        Finds the existing asset for this organisation and flexible asset type and PATCHes
        it, or creates one. There is deliberately at most one record per client per
        document - the whole point of the shape chosen for these is that a tech opens one
        record and reads the client, rather than paging through a policy list.

        IT Glue's 422s carry the useful detail in the response body rather than the status
        line, so failures are unwrapped before they are logged.
    .FUNCTIONALITY
        Internal
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory = $true)]$OrgId,
        [Parameter(Mandatory = $true)]$TypeId,
        [Parameter(Mandatory = $true)][hashtable]$Traits,
        [Parameter(Mandatory = $true)][string]$Label,
        $ObjectCount,
        [int]$TruncationCount = 0,
        $Tenant,
        $CompanyResult
    )

    $Existing = Invoke-ITGlueRequest -Path "/flexible_assets?filter[organization-id]=$OrgId&filter[flexible-asset-type-id]=$TypeId" -AllPages
    $ExistingAsset = $Existing | Select-Object -First 1

    $Payload = @{
        data = @{
            type       = 'flexible-assets'
            attributes = @{
                'organization-id'        = [int]$OrgId
                'flexible-asset-type-id' = [int]$TypeId
                traits                   = $Traits
            }
        }
    }

    if (-not $PSCmdlet.ShouldProcess("IT Glue organisation $OrgId", "$Label document")) { return }

    try {
        if ($ExistingAsset) {
            $null = Invoke-ITGlueRequest -Path "/flexible_assets/$($ExistingAsset.id)" -Method PATCH -Body $Payload -Raw
            $CompanyResult.Logs.Add("${Label}: updated asset $($ExistingAsset.id) ($ObjectCount objects).")
        } else {
            $Created = Invoke-ITGlueRequest -Path '/flexible_assets' -Method POST -Body $Payload -Raw
            $CompanyResult.Logs.Add("${Label}: created asset $($Created.data.id) ($ObjectCount objects).")
        }
        if ($TruncationCount -gt 0) {
            $CompanyResult.Logs.Add("${Label}: $TruncationCount section(s) truncated to fit IT Glue field limits.")
        }
    } catch {
        $Msg = $_.Exception.Message
        $Detail = ''
        try {
            if ($_.ErrorDetails -and $_.ErrorDetails.Message) {
                $Parsed = $_.ErrorDetails.Message | ConvertFrom-Json -ErrorAction Stop
                if ($Parsed.errors) { $Detail = ' | ' + (($Parsed.errors | ForEach-Object { "$($_.title): $($_.detail)" }) -join '; ') }
            }
        } catch {}
        $Full = "${Label}: ${Msg}${Detail}"
        $CompanyResult.Errors.Add($Full)
        Write-LogMessage -API 'ITGlueSync' -tenant $Tenant.defaultDomainName -message $Full -sev Warning
    }
}
