# Shared plumbing behind every CIPP -> IT Glue documentation asset. Two properties matter
# enough to pin: the count trait must be a string (IT Glue renders a Number field as "75.0"
# in a record a client may read), and Collection Notes must always say something - a record
# that is silent about its own completeness reads as complete when it is not.

BeforeAll {
    $RepoRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSCommandPath))
    . (Join-Path $RepoRoot 'Modules/CippExtensions/Private/ITGlue/Get-ITGlueFormattedField.ps1')
    . (Join-Path $RepoRoot 'Modules/CippExtensions/Private/ITGlue/Get-ITGlueFormattedBlock.ps1')
    . (Join-Path $RepoRoot 'Modules/CippExtensions/Private/ITGlue/Get-ITGlueDocumentHelpers.ps1')

    function New-Model([int]$Count = 42, $Notes = @()) {
        @{
            TenantName      = 'Acme Fabrication'
            TenantDomain    = 'acmefab.com'
            ObjectCount     = $Count
            CollectionNotes = $Notes
        }
    }
}

Describe 'Get-ITGlueDocumentIdentityTraits' {

    It 'writes the count as a string, not a number' {
        # A Number field renders as "42.0" in the IT Glue record.
        $Traits = Get-ITGlueDocumentIdentityTraits -Model (New-Model 42)
        $Traits['policy-count'] | Should -BeOfType [string]
        $Traits['policy-count'] | Should -Be '42'
    }

    It 'honours a different count trait name for other documents' {
        $Traits = Get-ITGlueDocumentIdentityTraits -Model (New-Model 7) -CountTrait 'object-count'
        $Traits['object-count'] | Should -Be '7'
        $Traits.ContainsKey('policy-count') | Should -BeFalse
    }

    It 'stamps tenant identity and a US Central timestamp' {
        $Traits = Get-ITGlueDocumentIdentityTraits -Model (New-Model)
        $Traits['tenant'] | Should -Be 'Acme Fabrication'
        $Traits['tenant-domain'] | Should -Be 'acmefab.com'
        # The operator reads this record in Texas; the zone must be stated, not implied.
        $Traits['last-synced'] | Should -Match '^\d{4}-\d{2}-\d{2} \d{2}:\d{2} (CDT|CST|UTC)$'
    }
}

Describe 'Get-ITGlueCollectionNotesHtml' {

    It 'states completeness explicitly when nothing failed' {
        $Html = Get-ITGlueCollectionNotesHtml -Model (New-Model) -Truncations ([System.Collections.Generic.List[object]]::new())
        $Html | Should -Match 'Every section was collected in full'
    }

    It 'records a section that could not be collected' {
        $Model = New-Model 10 @(@{ Section = 'Apps and Scripts'; Detail = 'Applications unavailable: boom' })
        $Html = Get-ITGlueCollectionNotesHtml -Model $Model -Truncations ([System.Collections.Generic.List[object]]::new())

        $Html | Should -Match 'Apps and Scripts \(not collected\)'
        $Html | Should -Match 'boom'
        $Html | Should -Not -Match 'Every section was collected in full'
    }

    It 'records truncated sections alongside failed ones' {
        $Trunc = [System.Collections.Generic.List[object]]::new()
        $Trunc.Add(@{ Section = 'Settings Catalog'; Detail = 'Showed 100 of 900 rows' })
        $Model = New-Model 10 @(@{ Section = 'RBAC'; Detail = 'no permission' })

        $Html = Get-ITGlueCollectionNotesHtml -Model $Model -Truncations $Trunc

        $Html | Should -Match 'RBAC \(not collected\)'
        $Html | Should -Match 'Settings Catalog \(truncated\)'
        $Html | Should -Match 'Showed 100 of 900 rows'
    }

    It 'always carries the source disclaimer so nobody hand-edits the record' {
        $Html = Get-ITGlueCollectionNotesHtml -Model (New-Model) -SourceLabel 'identity and access'
        $Html | Should -Match 'Generated by CIPP'
        $Html | Should -Match 'acmefab\.com'
        $Html | Should -Match 'identity and access'
        $Html | Should -Match 'overwritten on every sync'
    }

    It 'tolerates a null truncation list' {
        { Get-ITGlueCollectionNotesHtml -Model (New-Model) } | Should -Not -Throw
    }
}
