function New-CIPPPrinterScript {
    <#
    .SYNOPSIS
        Builds the PowerShell that installs a catalogue printer on a Windows endpoint.
    .DESCRIPTION
        Intune has no configuration service provider for TCP/IP port printers or for mapped
        print-server queues - the only printer settings in the settings catalog are the seven
        Universal Print ones. Those two printer types therefore ship as a generated script run
        by an Intune platform script, which is what this function produces.

        The generated script is idempotent: it is safe to re-run on a device that already has
        the printer, because Intune re-runs platform scripts.
    .PARAMETER Printer
        A catalogue entry. Requires Name and PrinterType; DirectIP additionally requires
        HostAddress and DriverName, ServerShare requires UNCPath.
    .EXAMPLE
        New-CIPPPrinterScript -Printer @{ Name = 'Reception'; PrinterType = 'DirectIP'; HostAddress = '10.0.0.20'; DriverName = 'HP Universal Printing PCL 6' }
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        $Printer
    )

    # Every catalogue value is operator-supplied free text that is about to be pasted into a
    # single-quoted PowerShell literal, so a lone apostrophe would end the string early and the
    # rest of the name would execute. Doubling it is the escape a single-quoted literal takes.
    function ConvertTo-CIPPPsLiteral {
        param($Value)
        if ($null -eq $Value) { return '' }
        # A newline is the second escape route: the name is also echoed into a '#' comment, and a
        # line break there would end the comment and put the remainder on an executable line.
        # Collapse all line breaks before doubling quotes.
        $Flattened = ([string]$Value) -replace '[\r\n]+', ' '
        return $Flattened.Replace("'", "''")
    }

    $Name = ConvertTo-CIPPPsLiteral -Value $Printer.Name
    if ([string]::IsNullOrWhiteSpace($Name)) { throw 'A catalogue printer must have a Name' }

    $Header = @"
# Generated by CIPP - do not edit on the device.
# Printer: $Name
`$ErrorActionPreference = 'Stop'

"@

    switch ($Printer.PrinterType) {
        'DirectIP' {
            if ([string]::IsNullOrWhiteSpace($Printer.HostAddress)) { throw 'A DirectIP printer must have a HostAddress' }
            if ([string]::IsNullOrWhiteSpace($Printer.DriverName)) { throw 'A DirectIP printer must have a DriverName' }

            $HostAddress = ConvertTo-CIPPPsLiteral -Value $Printer.HostAddress
            $DriverName = ConvertTo-CIPPPsLiteral -Value $Printer.DriverName
            # 9100 is the RAW printing default; only fall back when nothing was supplied.
            $PortNumber = if ($Printer.PortNumber) { [int]$Printer.PortNumber } else { 9100 }
            $PortName = "IP_$($Printer.HostAddress)"
            $PortNameLiteral = ConvertTo-CIPPPsLiteral -Value $PortName

            # Three ways a driver can reach the device, and the catalogue says which:
            #   Inbox     - Windows already ships it; Add-PrinterDriver just promotes it.
            #   Win32App  - an Intune Win32 app stages it first; same promotion, but the app is
            #               a prerequisite, so the script says so rather than failing opaquely.
            #   InfPath   - the script stages the INF itself with pnputil before promoting it.
            $DriverSource = if ($Printer.DriverSource) { [string]$Printer.DriverSource } else { 'Inbox' }
            if ($DriverSource -notin @('Inbox', 'Win32App', 'InfPath')) {
                throw "Unknown DriverSource '$DriverSource'. Expected Inbox, Win32App or InfPath."
            }

            $StagingBlock = ''
            if ($DriverSource -eq 'InfPath') {
                if ([string]::IsNullOrWhiteSpace($Printer.DriverInfPath)) {
                    throw 'A DriverSource of InfPath requires a DriverInfPath'
                }
                $InfPath = ConvertTo-CIPPPsLiteral -Value $Printer.DriverInfPath
                $StagingBlock = @"

# Stage the driver package into the driver store before promoting it. pnputil is idempotent:
# re-adding an already-staged package is a no-op, which matters because Intune re-runs this.
if (-not (Get-PrinterDriver -Name '$DriverName' -ErrorAction SilentlyContinue)) {
    if (-not (Test-Path -LiteralPath '$InfPath')) {
        throw "Driver INF not found at '$InfPath'. Stage the driver or correct the catalogue entry."
    }
    & pnputil.exe /add-driver '$InfPath' /install | Out-Null
}
"@
            } elseif ($DriverSource -eq 'Win32App') {
                $StagingBlock = @"

# Driver is staged by a separate Intune Win32 app. If that app has not landed yet this script
# fails here by design rather than creating a queue bound to a missing driver.
"@
            }

            $Body = @"
`$PortName = '$PortNameLiteral'

if (-not (Get-PrinterPort -Name `$PortName -ErrorAction SilentlyContinue)) {
    Add-PrinterPort -Name `$PortName -PrinterHostAddress '$HostAddress' -PortNumber $PortNumber
}
$StagingBlock
# Add-PrinterDriver only promotes a driver that is already in the driver store.
if (-not (Get-PrinterDriver -Name '$DriverName' -ErrorAction SilentlyContinue)) {
    Add-PrinterDriver -Name '$DriverName'
}

`$Existing = Get-Printer -Name '$Name' -ErrorAction SilentlyContinue
if (`$Existing) {
    # Re-point rather than recreate, so a changed IP or driver converges without losing the queue.
    Set-Printer -Name '$Name' -PortName `$PortName -DriverName '$DriverName'
} else {
    Add-Printer -Name '$Name' -DriverName '$DriverName' -PortName `$PortName
}
"@
        }
        'ServerShare' {
            if ([string]::IsNullOrWhiteSpace($Printer.UNCPath)) { throw 'A ServerShare printer must have a UNCPath' }
            $UNCPath = ConvertTo-CIPPPsLiteral -Value $Printer.UNCPath

            $Body = @"
# Runs in the user context: a mapped print-server queue belongs to the user's profile, so this
# script must be assigned with runAsAccount 'user'.
if (-not (Get-Printer -Name '$UNCPath' -ErrorAction SilentlyContinue)) {
    Add-Printer -ConnectionName '$UNCPath'
}
"@
        }
        'UniversalPrint' {
            # Universal Print is provisioned by the settings-catalog policy, never by a script.
            throw 'UniversalPrint printers deploy through the Intune settings catalog template, not a script. Use the Universal Print template instead.'
        }
        default {
            throw "Unknown PrinterType '$($Printer.PrinterType)'. Expected DirectIP, ServerShare or UniversalPrint."
        }
    }

    return ($Header + $Body)
}
